import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-200 min-h-screen p-20">
        <h1 className="py-10 text-3xl text-orange-600 text-center shadow-md bg-green-200">
          Home
        </h1>
      </main>
    </>
  );
}
